package com.example.keynest.data

import android.content.ContentValues
import androidx.sqlite.db.SupportSQLiteDatabase
import androidx.sqlite.db.SupportSQLiteOpenHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.example.keynest.data.migration.Migration_1_2
import com.google.common.truth.Truth.assertThat
import org.junit.After
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.annotation.Config
import java.io.File

/**
 * Verifies the [Migration_1_2] migration. Issue #9 Req 3.1, 3.3, 3.4, 6.1.
 *
 * We test the migration in isolation by driving it directly against a
 * `SupportSQLiteDatabase` constructed with the v1 schema (no
 * `last_used_at` column). This keeps the test self-contained -- it does
 * not depend on Room schema JSON files generated by KSP being committed
 * under `app/schemas/`, and it does not depend on Room's identity-hash
 * validation logic.
 *
 * Trade-off: this does NOT exercise Room's full open / upgrade / validate
 * pipeline. That end-to-end migration check is intentionally deferred to
 * a future task once the schema JSON files are produced by a local KSP
 * run (see impl-notes.md).
 */
@RunWith(AndroidJUnit4::class)
@Config(sdk = [33])
class Migration_1_2_Test {

    private val context = ApplicationProvider.getApplicationContext<android.content.Context>()
    private val dbName = "migration_test_${System.nanoTime()}.db"
    private var helper: SupportSQLiteOpenHelper? = null

    @After
    fun tearDown() {
        helper?.close()
        val file: File = context.getDatabasePath(dbName)
        if (file.exists()) file.delete()
        listOf("-journal", "-shm", "-wal").forEach { ext ->
            val side = File(file.absolutePath + ext)
            if (side.exists()) side.delete()
        }
    }

    @Test
    fun migrate_preservesExistingRow_andLeavesLastUsedAtNull() {
        // Arrange: build a v1 database with a single sample row.
        val db = openV1Database()
        insertV1Row(
            db,
            packageName = "com.example.target",
            username = "alice",
            label = "Example",
            createdAt = 100L,
            updatedAt = 200L,
        )

        // Act: apply the migration directly.
        Migration_1_2.migrate(db)

        // Assert: row still present, new column exists and is NULL.
        val cursor = db.query(
            "SELECT id, package_name, username, label, created_at, updated_at, last_used_at " +
                "FROM credentials"
        )
        cursor.use {
            assertThat(it.moveToFirst()).isTrue()
            assertThat(it.getString(it.getColumnIndexOrThrow("package_name")))
                .isEqualTo("com.example.target")
            assertThat(it.getString(it.getColumnIndexOrThrow("username"))).isEqualTo("alice")
            assertThat(it.getString(it.getColumnIndexOrThrow("label"))).isEqualTo("Example")
            assertThat(it.getLong(it.getColumnIndexOrThrow("created_at"))).isEqualTo(100L)
            assertThat(it.getLong(it.getColumnIndexOrThrow("updated_at"))).isEqualTo(200L)
            val lastUsedIdx = it.getColumnIndexOrThrow("last_used_at")
            assertThat(it.isNull(lastUsedIdx)).isTrue()
            assertThat(it.moveToNext()).isFalse() // only one row
        }
    }

    @Test
    fun migrate_addsColumn_andAllowsSubsequentWrites() {
        // Arrange
        val db = openV1Database()

        // Act
        Migration_1_2.migrate(db)

        // Assert: we can insert a row that writes the new column.
        val values = ContentValues().apply {
            put("package_name", "com.example.other")
            put("username", "bob")
            put("label", "Other")
            put("password_ciphertext", byteArrayOf(1, 2, 3))
            put("password_iv", ByteArray(12) { 0x10.toByte() })
            putNull("signature_sha256")
            putNull("signature_captured_at")
            put("created_at", 0L)
            put("updated_at", 0L)
            put("last_used_at", 12345L)
        }
        val rowId = db.insert(
            "credentials",
            android.database.sqlite.SQLiteDatabase.CONFLICT_ABORT,
            values,
        )
        assertThat(rowId).isGreaterThan(0L)

        val cursor = db.query("SELECT last_used_at FROM credentials WHERE id = $rowId")
        cursor.use {
            assertThat(it.moveToFirst()).isTrue()
            assertThat(it.getLong(0)).isEqualTo(12345L)
        }
    }

    @Test
    fun migrate_isIdempotentOnEmptyDatabase() {
        // Arrange: an empty v1 database.
        val db = openV1Database()

        // Act
        Migration_1_2.migrate(db)

        // Assert: count is 0 and column is queryable.
        val cursor = db.query("SELECT COUNT(*) FROM credentials")
        cursor.use {
            assertThat(it.moveToFirst()).isTrue()
            assertThat(it.getLong(0)).isEqualTo(0L)
        }
        val cursor2 = db.query("SELECT last_used_at FROM credentials LIMIT 1")
        cursor2.use {
            // moveToFirst returns false on empty result, which is fine.
            assertThat(it.columnNames.toList()).contains("last_used_at")
        }
    }

    // ---- v1 fixture helpers ---------------------------------------------

    /**
     * Opens (creating if needed) a database with the exact v1 schema. Keeps
     * the helper alive for the duration of the test so we can keep
     * interacting with the same connection.
     */
    private fun openV1Database(): SupportSQLiteDatabase {
        val factory = FrameworkSQLiteOpenHelperFactory()
        val configured = factory.create(
            SupportSQLiteOpenHelper.Configuration.builder(context)
                .name(dbName)
                .callback(object : SupportSQLiteOpenHelper.Callback(1) {
                    override fun onCreate(db: SupportSQLiteDatabase) {
                        db.execSQL(V1_CREATE_TABLE_SQL)
                        db.execSQL(V1_CREATE_INDEX_SQL)
                    }

                    override fun onUpgrade(
                        db: SupportSQLiteDatabase,
                        oldVersion: Int,
                        newVersion: Int,
                    ) = Unit
                })
                .build()
        )
        helper = configured
        return configured.writableDatabase
    }

    private fun insertV1Row(
        db: SupportSQLiteDatabase,
        packageName: String,
        username: String,
        label: String,
        createdAt: Long,
        updatedAt: Long,
    ) {
        val values = ContentValues().apply {
            put("package_name", packageName)
            put("username", username)
            put("label", label)
            put("password_ciphertext", byteArrayOf(1, 2, 3))
            put("password_iv", ByteArray(12) { 0x10.toByte() })
            putNull("signature_sha256")
            putNull("signature_captured_at")
            put("created_at", createdAt)
            put("updated_at", updatedAt)
        }
        db.insert("credentials", android.database.sqlite.SQLiteDatabase.CONFLICT_ABORT, values)
    }

    private companion object {
        // DDL identical to what Room generates for CredentialEntity at v1
        // (no last_used_at column).
        private const val V1_CREATE_TABLE_SQL = """
            CREATE TABLE IF NOT EXISTS `credentials` (
                `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                `package_name` TEXT NOT NULL,
                `username` TEXT NOT NULL,
                `label` TEXT NOT NULL,
                `password_ciphertext` BLOB NOT NULL,
                `password_iv` BLOB NOT NULL,
                `signature_sha256` BLOB,
                `signature_captured_at` INTEGER,
                `created_at` INTEGER NOT NULL,
                `updated_at` INTEGER NOT NULL
            )
        """
        private const val V1_CREATE_INDEX_SQL =
            "CREATE INDEX IF NOT EXISTS `index_credentials_package_name` ON `credentials` (`package_name`)"
    }
}
