package inc.goodanswers.keynest.security

import javax.crypto.Cipher
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM authenticated encryption wrapper backed by an Android Keystore
 * managed key (see [KeystoreKeyProvider]).
 *
 * Requirements:
 * - 1.2 - password is never written in plaintext to disk
 * - NFR 1.1 - AES-GCM with Keystore protected key
 * - NFR 1.2 - the raw key bytes never leave the Keystore
 *
 * GCM auth tag length is fixed at 128 bits (the only NIST-recommended value).
 * IV is generated by the platform Cipher on every `encrypt()` (a fresh 12 byte
 * IV per call), which combined with `setRandomizedEncryptionRequired(true)` on
 * the key spec guarantees IV uniqueness.
 */
open class AesGcmCipher(
    private val keyProvider: KeystoreKeyProvider,
) {

    /**
     * Encrypts [plaintext] with the Keystore-managed AES key.
     *
     * The returned [EncryptedBlob.iv] is the platform generated IV. Each call
     * to this function produces a distinct IV and therefore a distinct
     * ciphertext (verified by tests / NFR 1.1).
     *
     * The method is `open` so that JVM unit tests in pure-Kotlin modules can
     * substitute a non-Keystore implementation (the real AndroidKeyStore is
     * only available under Robolectric / instrumented tests).
     */
    open fun encrypt(plaintext: ByteArray): EncryptedBlob {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, keyProvider.getOrCreateKey())
        val ciphertext = cipher.doFinal(plaintext)
        // Cipher.iv returns the 12-byte GCM IV the platform picked.
        val iv = cipher.iv ?: error("AES/GCM cipher returned null IV")
        return EncryptedBlob(iv = iv.copyOf(), ciphertext = ciphertext)
    }

    /**
     * Decrypts [blob] using the IV bundled with it. The auth tag is validated
     * by GCM internally: if the ciphertext or AAD was tampered with, the
     * underlying [javax.crypto.AEADBadTagException] will propagate to the
     * caller (which the use-case layer surfaces as an opaque error so that no
     * sensitive byte is leaked to logs - NFR 1.3).
     */
    open fun decrypt(blob: EncryptedBlob): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        val spec = GCMParameterSpec(GCM_TAG_BITS, blob.iv)
        cipher.init(Cipher.DECRYPT_MODE, keyProvider.getOrCreateKey(), spec)
        return cipher.doFinal(blob.ciphertext)
    }

    companion object {
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val GCM_TAG_BITS = 128
    }
}
